-- 02_legg_hovslager_inn_i_handverker.sql
-- KJØRES I HÅNDVERKER-BASEN / RETTILOMMA-BASEN.
-- Lager hovslager-tabellene som mangler. Bruker IF NOT EXISTS, så den overskriver ikke eksisterende tabeller.

-- Viktig:
-- Dette scriptet lager STRUKTUREN. Det flytter ikke data fra en annen Supabase-base.
-- Data må evt. importeres etterpå med CSV/backup/restore.

create table if not exists public.hester (
  id bigint generated by default as identity primary key,
  kunde_id bigint not null references public.kunder(id) on delete restrict,
  navn text not null,
  rase text,
  notater text,
  sist_skodd date,
  neste_besok date,
  created_at timestamptz not null default now()
);

create index if not exists idx_hester_kunde_id on public.hester(kunde_id);
create index if not exists idx_hester_navn on public.hester(navn);

create table if not exists public.hov_jobber (
  id bigint generated by default as identity primary key,
  kunde_id bigint not null references public.kunder(id) on delete restrict,
  hest_id bigint references public.hester(id) on delete set null,
  dato date not null default current_date,
  jobbtype text,
  beskrivelse text,
  km numeric not null default 0,
  km_pris numeric not null default 0,
  arbeid_belop numeric not null default 0,
  varer_belop numeric not null default 0,
  mva numeric not null default 0,
  total numeric not null default 0,
  fakturert boolean not null default false,
  fakturanr text,
  created_at timestamptz not null default now()
);

create index if not exists idx_hov_jobber_kunde_id on public.hov_jobber(kunde_id);
create index if not exists idx_hov_jobber_hest_id on public.hov_jobber(hest_id);
create index if not exists idx_hov_jobber_dato on public.hov_jobber(dato);
create index if not exists idx_hov_jobber_fakturert on public.hov_jobber(fakturert);
create index if not exists idx_hov_jobber_fakturanr on public.hov_jobber(fakturanr);

create table if not exists public.hov_fakturaer (
  id bigint generated by default as identity primary key,
  fakturanr text not null unique,
  kunde_id bigint not null references public.kunder(id) on delete restrict,
  dato date not null default current_date,
  eks_mva numeric not null default 0,
  mva numeric not null default 0,
  inkl_mva numeric not null default 0,
  betalingsstatus text not null default 'ubetalt',
  betalt_belop numeric not null default 0,
  betalt_dato date,
  kreditert boolean not null default false,
  kreditert_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_hov_fakturaer_kunde_id on public.hov_fakturaer(kunde_id);
create index if not exists idx_hov_fakturaer_dato on public.hov_fakturaer(dato);
create index if not exists idx_hov_fakturaer_betalingsstatus on public.hov_fakturaer(betalingsstatus);

create table if not exists public.hov_kreditnotaer (
  id bigint generated by default as identity primary key,
  kreditnotanr text not null unique,
  fakturanr text not null,
  kunde_id bigint references public.kunder(id) on delete restrict,
  dato date not null default current_date,
  eks_mva numeric not null default 0,
  mva numeric not null default 0,
  inkl_mva numeric not null default 0,
  grunn text,
  created_at timestamptz not null default now()
);

create index if not exists idx_hov_kreditnotaer_fakturanr on public.hov_kreditnotaer(fakturanr);
create index if not exists idx_hov_kreditnotaer_kunde_id on public.hov_kreditnotaer(kunde_id);

-- Sikkerhetsnett: hvis tabellene finnes fra før, men mangler noen kolonner, legg dem til.
alter table public.hester add column if not exists kunde_id bigint;
alter table public.hester add column if not exists navn text;
alter table public.hester add column if not exists rase text;
alter table public.hester add column if not exists notater text;
alter table public.hester add column if not exists sist_skodd date;
alter table public.hester add column if not exists neste_besok date;
alter table public.hester add column if not exists created_at timestamptz default now();

alter table public.hov_jobber add column if not exists kunde_id bigint;
alter table public.hov_jobber add column if not exists hest_id bigint;
alter table public.hov_jobber add column if not exists dato date default current_date;
alter table public.hov_jobber add column if not exists jobbtype text;
alter table public.hov_jobber add column if not exists beskrivelse text;
alter table public.hov_jobber add column if not exists km numeric default 0;
alter table public.hov_jobber add column if not exists km_pris numeric default 0;
alter table public.hov_jobber add column if not exists arbeid_belop numeric default 0;
alter table public.hov_jobber add column if not exists varer_belop numeric default 0;
alter table public.hov_jobber add column if not exists mva numeric default 0;
alter table public.hov_jobber add column if not exists total numeric default 0;
alter table public.hov_jobber add column if not exists fakturert boolean default false;
alter table public.hov_jobber add column if not exists fakturanr text;
alter table public.hov_jobber add column if not exists created_at timestamptz default now();

alter table public.hov_fakturaer add column if not exists fakturanr text;
alter table public.hov_fakturaer add column if not exists kunde_id bigint;
alter table public.hov_fakturaer add column if not exists dato date default current_date;
alter table public.hov_fakturaer add column if not exists eks_mva numeric default 0;
alter table public.hov_fakturaer add column if not exists mva numeric default 0;
alter table public.hov_fakturaer add column if not exists inkl_mva numeric default 0;
alter table public.hov_fakturaer add column if not exists betalingsstatus text default 'ubetalt';
alter table public.hov_fakturaer add column if not exists betalt_belop numeric default 0;
alter table public.hov_fakturaer add column if not exists betalt_dato date;
alter table public.hov_fakturaer add column if not exists kreditert boolean default false;
alter table public.hov_fakturaer add column if not exists kreditert_at timestamptz;
alter table public.hov_fakturaer add column if not exists created_at timestamptz default now();

alter table public.hov_kreditnotaer add column if not exists kreditnotanr text;
alter table public.hov_kreditnotaer add column if not exists fakturanr text;
alter table public.hov_kreditnotaer add column if not exists kunde_id bigint;
alter table public.hov_kreditnotaer add column if not exists dato date default current_date;
alter table public.hov_kreditnotaer add column if not exists eks_mva numeric default 0;
alter table public.hov_kreditnotaer add column if not exists mva numeric default 0;
alter table public.hov_kreditnotaer add column if not exists inkl_mva numeric default 0;
alter table public.hov_kreditnotaer add column if not exists grunn text;
alter table public.hov_kreditnotaer add column if not exists created_at timestamptz default now();

-- RLS: av inntil videre, siden du sa RLS ikke er på nå. Kan skrus på senere per kunde.
alter table public.hester disable row level security;
alter table public.hov_jobber disable row level security;
alter table public.hov_fakturaer disable row level security;
alter table public.hov_kreditnotaer disable row level security;

-- Kontroll etter opprettelse
select
  table_name,
  column_name,
  data_type
from information_schema.columns
where table_schema = 'public'
  and table_name in ('hester', 'hov_jobber', 'hov_fakturaer', 'hov_kreditnotaer')
order by table_name, ordinal_position;
