-- Kjør denne hvis Lagre oppsett gir RLS/policy-feil.
create table if not exists public.beh_firma (
  id bigint generated by default as identity primary key,
  navn text,
  firmanavn text,
  adresse text,
  telefon text,
  epost text,
  orgnr text,
  org_nr text,
  mva_nr text,
  kontonr text,
  kontonummer text,
  vipps_nummer text,
  vipps_mottaker text,
  logo_url text,
  brevhode_tekst text,
  brevfot_tekst text,
  created_at timestamptz not null default now()
);

alter table public.beh_firma enable row level security;
drop policy if exists "beh_firma all users" on public.beh_firma;
create policy "beh_firma all users" on public.beh_firma
for all to anon, authenticated using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('bilder', 'bilder', true)
on conflict (id) do update set public = true;

drop policy if exists "bilder all users read" on storage.objects;
drop policy if exists "bilder all users insert" on storage.objects;
drop policy if exists "bilder all users update" on storage.objects;

create policy "bilder all users read" on storage.objects
for select to anon, authenticated using (bucket_id = 'bilder');

create policy "bilder all users insert" on storage.objects
for insert to anon, authenticated with check (bucket_id = 'bilder');

create policy "bilder all users update" on storage.objects
for update to anon, authenticated using (bucket_id = 'bilder') with check (bucket_id = 'bilder');
