-- Rett i Lomma - Hestebehandler / Behandler
-- EGEN app med beh_ foran alle app-tabeller.
-- Kjør hele scriptet i Supabase SQL Editor før første innlogging.
-- Etterpå: Authentication -> Users -> Add user.

create extension if not exists pgcrypto;

create table if not exists public.beh_kunder (
  id bigint generated by default as identity primary key,
  navn text not null,
  adresse text,
  epost text,
  telefon text,
  kontaktperson text,
  notater text,
  created_at timestamptz not null default now()
);

create table if not exists public.beh_hester (
  id bigint generated by default as identity primary key,
  kunde_id bigint references public.beh_kunder(id) on delete cascade,
  navn text not null,
  rase text,
  fodt date,
  kjonn text,
  notater text,
  sist_skodd date,
  neste_besok date,
  created_at timestamptz not null default now()
);

create table if not exists public.beh_behandlinger (
  id bigint generated by default as identity primary key,
  kunde_id bigint references public.beh_kunder(id) on delete set null,
  hest_id bigint references public.beh_hester(id) on delete set null,
  dato date not null default current_date,
  behandlingtype text,
  jobbtype text,
  beskrivelse text,
  anbefaling text,
  neste_oppfolging date,
  km numeric default 0,
  km_pris numeric default 0,
  arbeid_belop numeric default 0,
  varer_belop numeric default 0,
  mva numeric default 0,
  total numeric default 0,
  fakturert boolean not null default false,
  fakturanr text,
  created_at timestamptz not null default now()
);

create table if not exists public.beh_behandling_bilder (
  id uuid primary key default gen_random_uuid(),
  behandling_id bigint references public.beh_behandlinger(id) on delete cascade,
  filnavn text,
  filsti text,
  bilde_url text,
  bildetekst text,
  created_at timestamptz not null default now()
);

create table if not exists public.beh_fakturaer (
  id bigint generated by default as identity primary key,
  fakturanr text unique not null,
  kunde_id bigint references public.beh_kunder(id) on delete set null,
  dato date not null default current_date,
  eks_mva numeric default 0,
  mva numeric default 0,
  inkl_mva numeric default 0,
  betalingsstatus text not null default 'ubetalt',
  betalt_belop numeric default 0,
  betalt_dato date,
  kreditert boolean not null default false,
  kreditert_dato date,
  kreditnota_nr text,
  created_at timestamptz not null default now()
);

create table if not exists public.beh_kreditnotaer (
  id bigint generated by default as identity primary key,
  kreditnotanr text unique not null,
  fakturanr text,
  kunde_id bigint references public.beh_kunder(id) on delete set null,
  dato date not null default current_date,
  eks_mva numeric default 0,
  mva numeric default 0,
  inkl_mva numeric default 0,
  grunn text,
  created_at timestamptz not null default now()
);

create table if not exists public.beh_priser (
  id bigint generated by default as identity primary key,
  navn text not null,
  pris numeric not null default 0,
  sortering integer not null default 0,
  aktiv boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.beh_firma (
  id bigint generated by default as identity primary key,
  navn text,
  firmanavn text,
  adresse text,
  telefon text,
  epost text,
  orgnr text,
  org_nr text,
  mva_nr text,
  kontonr text,
  kontonummer text,
  vipps_nummer text,
  vipps_mottaker text,
  logo_url text,
  brevhode_tekst text,
  brevfot_tekst text,
  created_at timestamptz not null default now()
);

create table if not exists public.beh_faktura_varer (
  id bigint generated by default as identity primary key,
  fakturanr text,
  navn text,
  antall numeric default 1,
  pris numeric default 0,
  mva numeric default 0,
  created_at timestamptz not null default now()
);

insert into public.beh_priser (navn, pris, sortering, aktiv)
select * from (values
  ('Massasje hest', 900, 10, true),
  ('Laserbehandling', 750, 20, true),
  ('Akupunktur', 950, 30, true),
  ('Osteopati / mobilisering', 1100, 40, true),
  ('Oppfølgingstime', 650, 50, true)
) as v(navn, pris, sortering, aktiv)
where not exists (select 1 from public.beh_priser);

insert into storage.buckets (id, name, public)
values ('bilder', 'bilder', true)
on conflict (id) do nothing;

alter table public.beh_kunder enable row level security;
alter table public.beh_hester enable row level security;
alter table public.beh_behandlinger enable row level security;
alter table public.beh_behandling_bilder enable row level security;
alter table public.beh_fakturaer enable row level security;
alter table public.beh_kreditnotaer enable row level security;
alter table public.beh_priser enable row level security;
alter table public.beh_firma enable row level security;
alter table public.beh_faktura_varer enable row level security;

do $$
declare t text;
begin
  foreach t in array array[
    'beh_kunder','beh_hester','beh_behandlinger','beh_behandling_bilder',
    'beh_fakturaer','beh_kreditnotaer','beh_priser','beh_firma','beh_faktura_varer'
  ] loop
    execute format('drop policy if exists "%s authenticated all" on public.%I', t, t);
    execute format('create policy "%s authenticated all" on public.%I for all to authenticated using (true) with check (true)', t, t);
  end loop;
end $$;

drop policy if exists "bilder authenticated read" on storage.objects;
drop policy if exists "bilder authenticated insert" on storage.objects;
drop policy if exists "bilder authenticated update" on storage.objects;
drop policy if exists "bilder authenticated delete" on storage.objects;

create policy "bilder authenticated read"
on storage.objects for select to authenticated
using (bucket_id = 'bilder');

create policy "bilder authenticated insert"
on storage.objects for insert to authenticated
with check (bucket_id = 'bilder');

create policy "bilder authenticated update"
on storage.objects for update to authenticated
using (bucket_id = 'bilder') with check (bucket_id = 'bilder');

create policy "bilder authenticated delete"
on storage.objects for delete to authenticated
using (bucket_id = 'bilder');
